# Generated by Django 4.0.4 on 2022-05-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usr',
        ),
    ]
