# Generated by Django 4.0.4 on 2022-05-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_usr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('desc', models.EmailField(max_length=100)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('disabled', models.BooleanField(default=False)),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
    ]
