# Generated by Django 4.0.4 on 2022-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
