# Generated by Django 4.0.4 on 2022-05-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
