# Generated by Django 4.0.4 on 2022-05-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_queries_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='subtype',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='usr',
            name='type',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
